import { router, json, error, db, requireAuth } from '@appdeploy/sdk';
type Product={id:string;name:string;price:number;old?:number;shop:string;category:string;rating:number;reviews:number;image:string;commission:number;stock:number;description:string;badge?:string};
type CartItem={productId:string;quantity:number};
type Order={orderId:string;userId:string;items:Array<{productId:string;quantity:number;shop:string;price:number}>;total:number;delivery:number;status:string;tracking:string;address:string;sellers:string[];createdAt:string};
const seedProducts:Product[]=[
{id:'1',name:'iPhone 11 64GB',price:30000,old:34000,shop:'iPhone Place Kenya',category:'Phones',rating:4.8,reviews:127,image:'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=900&q=85',commission:10,stock:8,description:'Tested iPhone 11 64GB from a verified Kenyan technology seller.',badge:'Hot Deal'},
{id:'2',name:'Samsung Galaxy A55 5G',price:35999,old:39999,shop:'Tech Hub Kenya',category:'Phones',rating:4.7,reviews:89,image:'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=900&q=85',commission:8,stock:12,description:'Modern 5G smartphone with a bright display and all-day battery.',badge:'Top Rated'},
{id:'3',name:'Premium Running Sneakers',price:2500,old:3500,shop:'Urban Kicks KE',category:'Fashion',rating:4.6,reviews:214,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',commission:12,stock:31,description:'Comfort-focused everyday running sneakers.',badge:'Flash Sale'},
{id:'4',name:'Wireless ANC Headphones',price:4200,old:5500,shop:'Sound House',category:'Electronics',rating:4.9,reviews:74,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',commission:10,stock:16,description:'Wireless over-ear headphones with active noise cancellation.',badge:'Best Seller'},
{id:'5',name:'Smart Watch Series 9',price:4800,old:6500,shop:'Gadget World KE',category:'Electronics',rating:4.5,reviews:156,image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85',commission:15,stock:22,description:'Everyday smartwatch for notifications and activity tracking.',badge:'Creator Pick'},
{id:'6',name:'Oversized Cotton Hoodie',price:2200,old:2800,shop:'Nairobi Streetwear',category:'Fashion',rating:4.8,reviews:61,image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85',commission:14,stock:44,description:'Soft heavyweight cotton hoodie with a relaxed oversized fit.',badge:'Trending'},
{id:'7',name:'Portable Power Bank 20,000mAh',price:2800,old:3500,shop:'Tech Hub Kenya',category:'Electronics',rating:4.7,reviews:118,image:'https://images.unsplash.com/photo-1609592424811-2d2a3d9c0c3d?auto=format&fit=crop&w=900&q=85',commission:9,stock:27,description:'High-capacity portable power bank designed for daily charging.',badge:'Value Pick'},
{id:'8',name:'Air Fryer 5L',price:7200,old:8500,shop:'HomePlus Kenya',category:'Home',rating:4.6,reviews:48,image:'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=900&q=85',commission:11,stock:9,description:'5-litre air fryer for convenient low-oil cooking.',badge:'Home Pick'}
];
const getRows=async<T>(table:string,limit=100)=>db.list<T>(table,{limit});
async function userRecord(userId:string){const r=await db.list('profiles',{filter:{userId},limit:1});return r.items[0]||null}
async function ensureProfile(userId:string,name?:string,email?:string){const existing=await userRecord(userId);if(existing)return existing;const [id]=await db.add('profiles',[{userId,name:name||'Marketplace User',email:email||'',createdAt:new Date().toISOString()}]);return id?{id,userId,name:name||'Marketplace User',email:email||''}:null}
export const handler=router({
'GET /api/_healthcheck':[async()=>json({message:'Success',version:'15'})],
'GET /api/products':[async()=>{const r=await getRows<Product>('products',100);if(r.items.length)return json({products:r.items});const ids=await db.add('products',seedProducts);const seeded=seedProducts.map((p,i)=>({...p,id:ids[i]||p.id}));return json({products:seeded})}],
'GET /api/shops':[async()=>{const r=await getRows('shops',100);return json({shops:r.items})}],
'GET /api/me':[requireAuth(),async(ctx)=>{const p=await ensureProfile(ctx.user!.userId,ctx.user!.name,ctx.user!.email);return json({profile:p,user:ctx.user})}],
'GET /api/cart':[requireAuth(),async(ctx)=>{const r=await db.list<CartItem>('cart_items',{filter:{userId:ctx.user!.userId},limit:100});return json({items:r.items})}],
'PUT /api/cart':[requireAuth(),async(ctx)=>{const x=ctx.body as {items?:CartItem[]};if(!Array.isArray(x.items))return error('Cart items are required',400);const existing=await db.list<CartItem>('cart_items',{filter:{userId:ctx.user!.userId},limit:100});if(existing.items.length)await db.delete('cart_items',existing.items.map(i=>i.id));if(x.items.length)await db.add('cart_items',x.items.map(i=>({userId:ctx.user!.userId,productId:i.productId,quantity:Math.max(1,i.quantity)})));return json({saved:true,items:x.items})}],
'GET /api/wishlist':[requireAuth(),async(ctx)=>{const r=await db.list('wishlist',{filter:{userId:ctx.user!.userId},limit:100});return json({items:r.items})}],
'PUT /api/wishlist':[requireAuth(),async(ctx)=>{const x=ctx.body as {productIds?:string[]};if(!Array.isArray(x.productIds))return error('Wishlist is required',400);const r=await db.list('wishlist',{filter:{userId:ctx.user!.userId},limit:100});if(r.items.length)await db.delete('wishlist',r.items.map(i=>i.id));if(x.productIds.length)await db.add('wishlist',x.productIds.map(productId=>({userId:ctx.user!.userId,productId})));return json({saved:true,productIds:x.productIds})}],
'GET /api/orders':[requireAuth(),async(ctx)=>{const r=await db.list<Order>('orders',{filter:{userId:ctx.user!.userId},limit:100});return json({orders:r.items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}],
'POST /api/orders':[requireAuth(),async(ctx)=>{const x=ctx.body as {items?:Array<{productId:string;quantity:number;shop:string;price:number}>;total?:number;delivery?:number;address?:string;sellers?:string[]};if(!Array.isArray(x.items)||!x.items.length||!x.address?.trim()||!x.total||x.total<=0)return error('Valid order details are required',400);const o:Order={orderId:`TM-${Date.now().toString().slice(-8)}`,userId:ctx.user!.userId,items:x.items,total:x.total,delivery:x.delivery||0,status:'Payment confirmed',tracking:`TKM-${Math.random().toString(36).slice(2,8).toUpperCase()}`,address:x.address.trim(),sellers:x.sellers||[],createdAt:new Date().toISOString()};const [id]=await db.add('orders',[o]);if(!id)return error('Could not create order',500);return json({order:{...o,id}})}],
'POST /api/shops':[requireAuth(),async(ctx)=>{const x=ctx.body as {name?:string;location?:string;category?:string};if(!x.name?.trim())return error('Shop name is required',400);const existing=await db.list('shops',{filter:{ownerId:ctx.user!.userId},limit:1});if(existing.items.length)return json({shop:existing.items[0],existing:true});const [id]=await db.add('shops',[{ownerId:ctx.user!.userId,name:x.name.trim(),location:x.location||'Kenya',category:x.category||'General',followers:0,verified:false,status:'pending_verification',createdAt:new Date().toISOString()}]);return id?json({shop:{id,name:x.name.trim(),status:'pending_verification'}}):error('Could not create shop',500)}],
'GET /api/my-shop':[requireAuth(),async(ctx)=>{const r=await db.list('shops',{filter:{ownerId:ctx.user!.userId},limit:1});return json({shop:r.items[0]||null})}],
'GET /api/my-shop/products':[requireAuth(),async(ctx)=>{const shop=await db.list('shops',{filter:{ownerId:ctx.user!.userId},limit:1});if(!shop.items.length)return json({products:[]});const r=await db.list('seller_products',{filter:{ownerId:ctx.user!.userId},limit:100});return json({products:r.items})}],
'POST /api/my-shop/products':[requireAuth(),async(ctx)=>{const x=ctx.body as {name?:string;price?:number;stock?:number;category?:string;image?:string;description?:string};if(!x.name?.trim()||!x.price||x.price<=0||x.stock===undefined||x.stock<0)return error('Product name, price and stock are required',400);const [id]=await db.add('seller_products',[{ownerId:ctx.user!.userId,name:x.name.trim(),price:x.price,stock:x.stock,category:x.category||'General',image:x.image||'',description:x.description||'',status:'draft',createdAt:new Date().toISOString()}]);return id?json({product:{id,...x,status:'draft'}}):error('Could not create product',500)}],
'GET /api/payment/config':[async()=>json({livePaymentsEnabled:false,methods:['M-Pesa','Card'],currency:'KES'})],
'POST /api/payment/test':[async({body})=>{const x=body as {orderId?:string;amount?:number;method?:'M-Pesa'|'Card'};if(!x.orderId||!x.amount||x.amount<=0||!x.method)return error('Invalid test payment',400);return json({transaction:{id:`TX-${Date.now()}`,orderId:x.orderId,amount:x.amount,currency:'KES',method:x.method,status:'verified',createdAt:new Date().toISOString()}})}],
'POST /api/protection/confirm':[async({body})=>{const x=body as {orderId?:string};if(!x.orderId)return error('Order ID is required',400);return json({orderId:x.orderId,status:'protection_period',payout:'pending'})}],
'POST /api/protection/dispute':[async({body})=>{const x=body as {orderId?:string;reason?:string};if(!x.orderId||!x.reason)return error('Order ID and reason are required',400);return json({dispute:{id:`DSP-${Date.now()}`,orderId:x.orderId,reason:x.reason,status:'open',payout:'hold'}})}],
'POST /api/protection/resolve':[async({body})=>{const x=body as {disputeId?:string;resolution?:'refund'|'release'};if(!x.disputeId||!x.resolution)return error('Dispute or resolution is invalid',400);return json({dispute:{id:x.disputeId,status:x.resolution==='refund'?'resolved_refund':'resolved_release',payout:x.resolution==='refund'?'hold':'released'}})}]
});